theme: minima
title: Traveling Through Morelos
author: DANAEGO
email: dgo84588@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog you will find places to visit in Morelos,
  either to relax, have fun or to eat. Enojy your stay!!!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
